version: 2
updates:
  # Track GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  
  # Track Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

